name: BD
favicon: null
layout_spectrum: 0.35088373627513647
typography_spectrum: 0.62471
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#fdfdfd'
    - '#f3fd1e'
    - '#a5a739'
    - '#3b3b3b'
  brandStrength: 0.20755743188783526
  lightness: 0.7520745587535203
  saturation: 0.44908168935216963
  rhythmicContrast: 0.27450485806912184
purpose: []
